### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by kappaluppa** [andyhawkes/ps-paths-to-imagemap#1]
Hi,
I'm trying to use this in Photoshop CC. I get an errror:
Error 60: Not well-formed (invalid toke). line 510
-> <td id="LC18 class="block-code-js-file-line"> <span class="kd"function</span>.....
And it goes on.
http://screencast.com/t/nikMDhvqjOww
 Any idea about this? 
Thanks!
K

**Comment by andyhawkes** [comment]
Unable to replicate
